# Generated by Django 5.2.8 on 2025-11-06 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Alimento',
                'verbose_name_plural': 'Categorias de Alimentos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Categoria de Jogo',
                'verbose_name_plural': 'Categorias de Jogos',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ingredientes', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagem_url', models.CharField(blank=True, help_text='URL da imagem se não for upload', max_length=500)),
                ('ativo', models.BooleanField(default=True, help_text='Se o item está disponível no cardápio')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='bar.categoriaalimento')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'ordering': ['categoria__ordem', 'categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('detalhes', models.TextField(blank=True, help_text='Detalhes adicionais sobre o jogo')),
                ('tipo', models.CharField(help_text='Tipo de jogo (ex: Estratégia, RPG, etc.)', max_length=100)),
                ('jogadores_min', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('jogadores_max', models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)])),
                ('tempo_medio', models.CharField(help_text='Tempo médio de partida (ex: 30-60 min)', max_length=50)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('imagem_url', models.CharField(blank=True, help_text='URL da imagem se não for upload', max_length=500)),
                ('ativo', models.BooleanField(default=True, help_text='Se o jogo está disponível')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to='bar.categoriajogo')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['categoria__ordem', 'categoria__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CopiaJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único da cópia', max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True, help_text='Se a cópia está disponível para uso')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre o estado da cópia')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copias', to='bar.jogo')),
            ],
            options={
                'verbose_name': 'Cópia de Jogo',
                'verbose_name_plural': 'Cópias de Jogos',
                'ordering': ['jogo__nome', 'codigo'],
            },
        ),
    ]
